<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Data Mining</b></center>
<center><b><h1>K Means</b></center>
<center><b><h1>Meet pahiyar | 23010101180 </b></center>
<pre>

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:

# Load the BankChurners dataset
df = pd.read_csv("BankChurners.csv")
df.head()


,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998


In [3]:

# Use only Total_Trans_Amt column
X = df[['Total_Trans_Amt']].values
print(X[:10])  


[[1144]
 [1291]
 [1887]
 [1171]
 [ 816]
 [1088]
 [1330]
 [1538]
 [1350]
 [1441]]


In [4]:
def euclidean_distance(a, b):
    return np.sqrt(np.sum((np.array(a) - np.array(b))**2))

In [5]:
def update_cluster_center(cluster_data):
    sum = [0,0]
    for i in cluster_data:
        sum[0] = sum[0] + i[0]
        sum[1] = sum[1] + i[1]
    return [sum[0]/len(cluster_data), sum[1]/len(cluster_data)]

In [6]:

def kmeans(X, k, max_iters=100):
    # Randomly choose centroids
    np.random.seed(42)
    centroids = X[np.random.choice(range(len(X)), k, replace=False)]
    
    for _ in range(max_iters):
        clusters = [[] for _ in range(k)]
        
        # Assign points to nearest centroid
        for point in X:
            distances = [euclidean_distance(point, c) for c in centroids]
            cluster_idx = np.argmin(distances)
            clusters[cluster_idx].append(point)
        
        new_centroids = []
        for cluster in clusters:
            if cluster: 
                new_centroids.append(np.mean(cluster, axis=0))
            else:
                new_centroids.append(centroids[len(new_centroids)])
        
        new_centroids = np.array(new_centroids)
        
        # Convergence check
        if np.allclose(centroids, new_centroids):
            break
        centroids = new_centroids
    
    return centroids, clusters


In [7]:
kmeans(X, k=3)  # Example with 3 clusters

(array([[ 2045.90174873],
        [ 4895.74611399],
        [14602.672346  ]]),
 [[array([1144]),
   array([1291]),
   array([1887]),
   array([1171]),
   array([816]),
   array([1088]),
   array([1330]),
   array([1538]),
   array([1350]),
   array([1441]),
   array([1201]),
   array([1314]),
   array([1539]),
   array([1311]),
   array([1570]),
   array([1348]),
   array([1671]),
   array([1028]),
   array([1336]),
   array([1207]),
   array([1178]),
   array([692]),
   array([931]),
   array([1126]),
   array([1110]),
   array([1051]),
   array([1197]),
   array([1904]),
   array([1052]),
   array([1045]),
   array([1038]),
   array([1596]),
   array([1589]),
   array([1411]),
   array([1291]),
   array([1407]),
   array([1877]),
   array([966]),
   array([1464]),
   array([704]),
   array([1109]),
   array([1347]),
   array([1756]),
   array([1756]),
   array([1042]),
   array([1444]),
   array([1741]),
   array([1719]),
   array([1217]),
   array([1140]),
   array([1878]),
   arra

In [8]:
def euclidean_distance(a, b):
    return np.linalg.norm(np.array(a) - np.array(b))

In [9]:
def kmedoids(X, k, max_iters=100):
    np.random.seed(42)
    medoids = X[np.random.choice(range(len(X)), k, replace=False)]
    
    for _ in range(max_iters):
        clusters = [[] for _ in range(k)]
        
        # Assign points to nearest medoid
        for point in X:
            distances = np.linalg.norm(medoids - point, axis=1)  # vectorized
            cluster_idx = np.argmin(distances)
            clusters[cluster_idx].append(point)
        
        new_medoids = []
        for cluster in clusters:
            if cluster:
                cluster = np.array(cluster)
                # Compute distance matrix efficiently with NumPy
                dist_matrix = np.linalg.norm(cluster[:, None] - cluster[None, :], axis=2)
                total_distances = dist_matrix.sum(axis=1)
                new_medoids.append(cluster[np.argmin(total_distances)])
            else:
                # keep the old medoid if cluster empty
                new_medoids.append(medoids[len(new_medoids)])
        
        new_medoids = np.array(new_medoids)
        
        if np.allclose(medoids, new_medoids):
            break
        medoids = new_medoids
    
    return medoids, clusters

In [10]:
# Run k-medoids
medoids, clusters = kmedoids(X, k=3)

# Print results
print("Medoids:")
print(medoids)

print("\nClusters:")
for i, cluster in enumerate(clusters):
    print(f"Cluster {i+1}: {cluster}")

Medoids:
[[ 1914]
 [ 4460]
 [14625]]

Clusters:
Cluster 1: [array([1144]), array([1291]), array([1887]), array([1171]), array([816]), array([1088]), array([1330]), array([1538]), array([1350]), array([1441]), array([1201]), array([1314]), array([1539]), array([1311]), array([1570]), array([1348]), array([1671]), array([1028]), array([1336]), array([1207]), array([1178]), array([692]), array([931]), array([1126]), array([1110]), array([1051]), array([1197]), array([1904]), array([1052]), array([1045]), array([1038]), array([1596]), array([1589]), array([1411]), array([1291]), array([1407]), array([1877]), array([966]), array([1464]), array([704]), array([1109]), array([1347]), array([1756]), array([1756]), array([1042]), array([1444]), array([1741]), array([1719]), array([1217]), array([1140]), array([1878]), array([705]), array([1946]), array([1414]), array([602]), array([1052]), array([1295]), array([1424]), array([1359]), array([1168]), array([1097]), array([691]), array([1316]), arr